2024-07-11 20:59:30,985 - Initial population:
[[0 1 0 1]
 [1 1 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 1 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 0 1]
 [0 0 1 0]
 [0 0 0 1]
 [0 1 1 0]
 [1 0 1 0]
 [0 1 0 0]
 [0 1 1 1]
 [1 0 0 0]
 [0 1 1 1]
 [0 0 0 1]
 [1 1 1 0]
 [0 0 1 1]
 [0 1 1 1]]
2024-07-11 20:59:30,985 - Initial fitness values: [2, 2, 1, 1, 3, 0, 0, 3, 1, 1, 2, 2, 1, 3, 1, 3, 1, 3, 2, 3]

2024-07-11 20:59:30,985 - The percentage of selected genes for mutation (mutation_percent_genes) must be > 0 and <= 100 but (0) found.
Traceback (most recent call last):
  File "C:\Users\benke\AppData\Local\Programs\Python\Python310\lib\site-packages\pygad\pygad.py", line 735, in __init__
    raise ValueError(f"The percentage of selected genes for mutation (mutation_percent_genes) must be > 0 and <= 100 but ({mutation_percent_genes}) found.\n")
ValueError: The percentage of selected genes for mutation (mutation_percent_genes) must be > 0 and <= 100 but (0) found.

